  <div style="margin-top: 20px;">
        <a href="https://www.paypal.com/donate" target="_blank" style="background-color: #ff9800; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-size: 18px;">💖 Sponsor Us</a>
    </div>
    </footer>
</body>
</html>
